Added C++ Conditional Statements
Riddhi9570/HackerrankPracticeProblems pull request #49
Opened 2022-09-30 20:34 UTC by Rohan-G

### Issue Number:

This submission will close the issue #11

### Submissions Checklist:

* [x] Have you followed the guidelines in [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Riddhi9570/HackerrankPracticeProblems/pulls) for the same hackerrank problem?
* [x] Have you successfully submitted your code in hackerrank?
* [x] Have you ensured that you have put the files in appropriate folders? (Folders are made according to the subdomain of hackerrank practice problems).
* [x] Have you updated [README.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/README.md)?

### Hacktoberfest Contributor:

* [x] Are you a hacktoberfest contributor?

### Hackerrank Problem Link:

https://www.hackerrank.com/challenges/c-tutorial-conditional-if-else/problem

### Submitted Hackerrank Solution Link:

https://www.hackerrank.com/challenges/c-tutorial-conditional-if-else/submissions/code/293488598

### Any other changes you made or something you would like to mention?

NA

2022-09-30 20:56 UTC, Riddhi9570 requested changes
Hey, thanks for contributing. Following changes are requested:-

- Please put the file "Conditional Statements.cpp" inside the "C++/Introduction" folder instead of making a new folder "C++/Conditional Statements" as this question comes under the Introduction subdomain of hackerrank.

2022-10-01 06:32 UTC, Rohan-G commented
@Riddhi9570
Made requested changes. Please review

2022-10-01 07:15 UTC, Riddhi9570 approved these changes

2022-10-01 07:16 UTC, Riddhi9570 approved these changes
Thanks for your contribution! @Rohan-G

2022-10-01 07:16 UTC, merged